#include "main.h"

enum ENUM_SEVSEG_CHAR {
	ENUM_SEVSEG_0 = 0, ENUM_SEVSEG_1, ENUM_SEVSEG_2
	, ENUM_SEVSEG_3, ENUM_SEVSEG_4, ENUM_SEVSEG_5
	, ENUM_SEVSEG_6, ENUM_SEVSEG_7, ENUM_SEVSEG_8
	, ENUM_SEVSEG_9, ENUM_SEVSEG_A, ENUM_SEVSEG_b
	, ENUM_SEVSEG_c, ENUM_SEVSEG_d, ENUM_SEVSEG_E
	, ENUM_SEVSEG_F, ENUM_SEVSEG_g, ENUM_SEVSEG_H
	, ENUM_SEVSEG_L, ENUM_SEVSEG_n, ENUM_SEVSEG_o
	, ENUM_SEVSEG_p, ENUM_SEVSEG_r, ENUM_SEVSEG_t
	, ENUM_SEVSEG_u, ENUM_SEVSEG_y
};

